"""add cited to retrievals

Revision ID: 307a48b91d03
Revises: f54e84a5c89a
Create Date: 2026-09-21 22:16:10.154985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '307a48b91d03'  # pragma: allowlist secret
down_revision: Union[str, None] = 'f54e84a5c89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-adjusted from the autogenerated diff: autogenerate also proposed
# dropping 'ix_doc_chunks_content_fts' — a recurring false positive
# (that GIN index is created via raw SQL in an earlier migration, not
# ORM metadata, so autogenerate doesn't see it and assumes it's extra;
# same thing happened in f54e84a5c89a). Removed here; only the new
# column is this migration's concern.


def upgrade() -> None:
    # Unlike f54e84a5c89a's status backfill, `False` is a permanently
    # correct default here (a pre-existing Retrieval genuinely wasn't
    # marked cited), not a one-time trust decision — so the
    # server_default stays, it isn't dropped after backfilling.
    op.add_column(
        "retrievals", sa.Column("cited", sa.Boolean(), nullable=False, server_default=sa.false())
    )


def downgrade() -> None:
    op.drop_column("retrievals", "cited")
