"""initial schema

Revision ID: 32080be745a1
Revises:
Create Date: 2026-09-14 03:06:53.650394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32080be745a1'  # pragma: allowlist secret
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ADR-0002/ADR-0004: doc_chunks.embedding needs the pgvector extension before
# that table is created.
_VECTOR_EXTENSION = "vector"

# Postgres ENUM types created implicitly by the tables below (via
# sa.Enum(..., name=...)) aren't dropped automatically when their table is
# dropped — they have to be dropped explicitly in downgrade(), in reverse
# order, or a later upgrade() will fail with "type already exists".
_ENUM_TYPE_NAMES = [
    "eval_run_type",
    "golden_set_source",
    "user_role",
    "ticket_status",
    "ticket_event_type",
    "decision_type",
    "guardrail_stage",
    "guardrail_check_type",
]


def upgrade() -> None:
    op.execute(f"CREATE EXTENSION IF NOT EXISTS {_VECTOR_EXTENSION}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('run_type', sa.Enum('CLASSIFICATION', 'FAITHFULNESS', 'JUDGE', 'SAFETY', name='eval_run_type'), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golden_set',
    sa.Column('ticket_text', sa.Text(), nullable=False),
    sa.Column('expected_label', sa.String(), nullable=False),
    sa.Column('expected_response', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SYNTHETIC', 'REAL', name='golden_set_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_docs',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doc_chunks',
    sa.Column('knowledge_doc_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_doc_id'], ['knowledge_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_doc_id', 'chunk_index')
    )
    op.create_table('tickets',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', 'ESCALATED', name='ticket_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.Enum('AUTO_RESPOND', 'DRAFT_FOR_REVIEW', 'ESCALATE', name='decision_type'), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_agent_decisions_confidence_score_range'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_events',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('CREATED', 'COMMENT_ADDED', 'STATUS_CHANGED', 'DRAFT_GENERATED', 'ESCALATED', 'RESOLVED', name='ticket_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardrail_checks',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('agent_decision_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('INPUT', 'OUTPUT', name='guardrail_stage'), nullable=False),
    sa.Column('check_type', sa.Enum('INJECTION', 'PII_REDACTION', 'SCHEMA_VALIDATION', 'GROUNDEDNESS', 'CONFIDENCE_THRESHOLD', name='guardrail_check_type'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrievals',
    sa.Column('agent_decision_id', sa.UUID(), nullable=False),
    sa.Column('doc_chunk_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('similarity_score >= 0 AND similarity_score <= 1', name='ck_retrievals_similarity_score_range'),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_chunk_id'], ['doc_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_decision_id', 'doc_chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrievals')
    op.drop_table('guardrail_checks')
    op.drop_table('ticket_events')
    op.drop_table('agent_decisions')
    op.drop_table('tickets')
    op.drop_table('doc_chunks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('knowledge_docs')
    op.drop_table('golden_set')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###

    for enum_name in _ENUM_TYPE_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute(f"DROP EXTENSION IF EXISTS {_VECTOR_EXTENSION}")
