"""add cost and latency columns to agent_decisions

Revision ID: afd9d13f8952
Revises: bb37425fc82f
Create Date: 2026-09-14 13:50:47.545925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd9d13f8952'  # pragma: allowlist secret
down_revision: Union[str, None] = 'bb37425fc82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_decisions', sa.Column('total_latency_ms', sa.Integer(), nullable=True))
    op.add_column('agent_decisions', sa.Column('claude_input_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_decisions', sa.Column('claude_output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_decisions', 'claude_output_tokens')
    op.drop_column('agent_decisions', 'claude_input_tokens')
    op.drop_column('agent_decisions', 'total_latency_ms')
    # ### end Alembic commands ###
