"""change doc_chunks embedding to 384 dims

Revision ID: bb37425fc82f
Revises: 32080be745a1
Create Date: 2026-09-14 04:22:07.497209

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bb37425fc82f'  # pragma: allowlist secret
down_revision: Union[str, None] = '32080be745a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doc_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doc_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###
