"""add status to knowledge_docs

Revision ID: f54e84a5c89a
Revises: b24f71c17ec8
Create Date: 2026-09-21 01:55:43.505500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f54e84a5c89a'
down_revision: Union[str, None] = 'b24f71c17ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-adjusted from the autogenerated diff: autogenerate also proposed
# dropping 'ix_doc_chunks_content_fts' — a false positive (that GIN
# index is created via raw SQL in an earlier migration, not ORM
# metadata, so autogenerate doesn't see it and assumes it's extra).
# Removed here; only the new column is this migration's concern.

knowledge_doc_status = postgresql.ENUM(
    "PROCESSING", "PENDING_REVIEW", "APPROVED", "REJECTED", "FAILED",
    name="knowledge_doc_status",
)


def upgrade() -> None:
    knowledge_doc_status.create(op.get_bind())
    # server_default backfills every existing row to APPROVED — already-
    # trusted content shouldn't silently vanish from search behind the
    # new review gate (see ADR-0017). Dropped immediately after: the ORM
    # model already carries its own Python-side default for the normal
    # SQLAlchemy insert path, and this avoids a DB-level default quietly
    # masking a raw-SQL insert that forgot to set status.
    op.add_column(
        "knowledge_docs",
        sa.Column("status", knowledge_doc_status, nullable=False, server_default="APPROVED"),
    )
    op.alter_column("knowledge_docs", "status", server_default=None)


def downgrade() -> None:
    op.drop_column("knowledge_docs", "status")
    knowledge_doc_status.drop(op.get_bind())
